export enum AppView {
  TOOLBOX_OVERVIEW = 'TOOLBOX_OVERVIEW',
  TEMPLATE_BUILDER = 'TEMPLATE_BUILDER',
  CALIBRATION = 'CALIBRATION',
  INVENTORY = 'INVENTORY',
  REPORTS = 'REPORTS',
  SETTINGS = 'SETTINGS',
  TOOLBOX_WIZARD = 'TOOLBOX_WIZARD'
}
